name: dev_yahia
description: Portfolio for Yahia Salem (@DevYahia)

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # icons
  community_material_icon: ^5.9.55
  cupertino_icons: ^1.0.4
  # links
  url_launcher: ^6.0.17
  url_launcher_web: ^2.0.5
  mailto: ^2.0.0
  # image
  image_picker: ^0.8.4+4
  # misc
  fluttertoast: ^8.0.8
  url_strategy: ^0.2.0
  universal_html: ^2.0.8
  # firebase
  firebase_core: ^1.10.2
  cloud_firestore: ^3.1.1
  firebase_storage: ^10.2.0
  # ui
  google_fonts: ^2.1.0
  animated_text_kit: ^4.2.1
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
